[package]
name = "security-cam-viewer"
version = "0.1.0"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
shuttle-runtime = "0.27.0"
actix-web = "4.4.0"
shuttle-actix-web = "0.27.0"
tokio = "1.32.0"
serde = { version="1.0.192"}
anyhow = "1.0.75"
thiserror = "1.0.50"
actix-session = { version = "0.8.0", features = ["cookie-session"] }
toml = "0.8.8"
log = "0.4.20"
