[package]
name = "security-cam-viewer"
version = "0.1.0"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
shuttle-runtime = "0.27.0"
actix-web = "4.4.0"
shuttle-actix-web = "0.27.0"
tokio = "1.32.0"
